name: Release Pipeline

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  # Build for Windows
  build_windows:
    runs-on: windows-latest  # Use Windows runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: clippy

      - name: Build for Windows
        run: |
          cargo build --release
          mkdir -p output/win
          cp target/release/aid.exe output/win/aid.exe

  # Build for Linux
  build_linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: clippy

      - name: Build for Linux
        run: |
          cargo build --release
          mkdir -p output/linux
          cp target/release/aid output/linux/aid

  # Build for macOS
  build_macos:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: clippy

      - name: Build for macOS
        run: |
          cargo build --release
          mkdir -p output/osx
          cp target/release/aid output/osx/aid

  # Create a single GitHub release with all artifacts
  create_release:
    runs-on: ubuntu-latest
    needs: [build_windows, build_linux, build_macos]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate release tag
        id: tag
        run: |
          VERSION=0.1.0
          echo "::set-output name=release_tag::aid-${VERSION}"

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          files: |
            output/win/aid.exe
            output/linux/aid
            output/osx/aid
